apiVersion: apps/v1
kind: Deployment
metadata:
  name: srv1-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srv1-pod
  template:
    metadata:
      labels:
        app: srv1-pod
    spec:
      containers:
        - name: srv1
          image: ngoctd/srv1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
          - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: srv1-svc
spec:
  type: NodePort
  selector:
    app: srv1-pod
  ports:
  - port: 8001
    targetPort: 8001
    nodePort: 31102
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: srv2-depl
spec:
  selector:
    matchLabels:
      app: srv2-pod
  template:
    metadata:
      labels:
        app: srv2-pod
    spec:
      containers:
      - name: srv2
        image: ngoctd/srv2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8002
---
apiVersion: v1
kind: Service
metadata:
  name: srv2-svc
spec:
  selector:
    app: srv2-pod
  ports:
  - port: 8002
    targetPort: 8002

